mineral_catalog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from . import views

urlpatterns = [
    url(r'^minerals/', include('minerals.urls', namespace='minerals')),
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
]

minerals/urls.py
from django.conf.urls import url

from . import views

app_name = 'minerals'  # This line is now required for Django 2.0
urlpatterns = [
    url(r'^$', views.mineral_list, name='mineral_list'),
    url(r'(?P<mineral_id>\d+)/$', views.mineral_detail, name='mineral_detail'),
    url(r'random/', views.random_mineral, name='random_mineral'),
]

minerals/models.py
import random

from django.db import models


class Mineral(models.Model):

    # All of the fields are CharFields, because there is no user interaction,
    # so data validation doesn't need to happen
    # If user input were required, the field types would be more intentional
    name = models.CharField(max_length=255)
    image_filename = models.CharField(max_length=255)
    image_caption = models.CharField(max_length=255)
    group = models.CharField(max_length=255)
    category = models.CharField(max_length=255)
    formula = models.CharField(max_length=255)
    strunz_classification = models.CharField(max_length=255)
    color = models.CharField(max_length=255)
    crystal_system = models.CharField(max_length=255)
    unit_cell = models.CharField(max_length=255)
    crystal_symmetry = models.CharField(max_length=255)
    cleavage = models.CharField(max_length=255)
    mohs_scale_hardness = models.CharField(max_length=255)
    luster = models.CharField(max_length=255)
    streak = models.CharField(max_length=255)
    diaphaneity = models.CharField(max_length=255)
    optical_properties = models.CharField(max_length=255)
    refractive_index = models.CharField(max_length=255)
    crystal_habit = models.CharField(max_length=255)
    specific_gravity = models.CharField(max_length=255)

mineral_catalog/views.py
from django.shortcuts import render


def index(request):
    """Shows a welcome message and a link to view all minerals"""
    return render(request, 'index.html')

minerals/views.py
import random

from django.db.models.aggregates import Count
from django.forms.models import model_to_dict
from django.shortcuts import get_object_or_404, render

from . import models


# List of names for order, and for skipping columns from the database not
# in this list
NAMES = [
    'group',
    'category',
    'formula',
    'strunz_classification',
    'color',
    'crystal_system',
    'unit_cell',
    'crystal_symmetry',
    'cleavage',
    'mohs_scale_hardness',
    'luster',
    'streak',
    'diaphaneity',
    'optical_properties',
    'refractive_index',
    'crystal_habit',
    'specific_gravity',
]


def mineral_list(request):
    """Shows the entire list of minerals"""
    minerals = models.Mineral.objects.all()
    return render(request, 'minerals/mineral_list.html',
                  {'minerals': minerals})


def mineral_detail(request, mineral_id):
    """Shows the detail view of a single mineral"""

    # Values is used instead of get to turn the output into a dictionary
    # This makes it possible to iterate through the key-value pair
    mineral = models.Mineral.objects.filter(id=mineral_id).values().first()
    prev_next = get_prev_next(mineral_id)
    return render(request, 'minerals/mineral_detail.html',
                  {'mineral': mineral, 'names': NAMES, 'prev_next': prev_next})


# Note that a template tag version was successfully created to do this same
# function, but this version was chosen, as the template tag version hit the
# database on every page load, whereas this only hits the database when
# a random mineral is sought
def random_mineral(request):
    """Shows the detail view of a single random mineral"""

    # Gets random index based on the full count of minerals in the database
    count = models.Mineral.objects.aggregate(count=Count('id'))['count']
    random_index = random.randint(0, count - 1)

    # Get the values of the mineral by the random index
    mineral = models.Mineral.objects.all().values()[random_index]
    prev_next = get_prev_next(mineral.get('id'))
    return render(request, 'minerals/mineral_detail.html',
                  {'mineral': mineral, 'names': NAMES, 'prev_next': prev_next})


def get_prev_next(mineral_id):
    """Generates a dictionary to provide the template the ID and name of the
    previous and next minerals alphabetically"""
    prev_mineral = (models.Mineral.objects
                    .filter(id__lt=mineral_id)
                    .exclude(id=mineral_id)
                    .order_by('-id')
                    .first())
    next_mineral = (models.Mineral.objects
                    .filter(id__gt=mineral_id)
                    .exclude(id=mineral_id)
                    .order_by('id')
                    .first())
    # Detects if the provided mineral ID is the first or last in the database
    # and sends the appropriate data if it's one of the ends
    if not prev_mineral:
        return {'next': {'id': next_mineral.id, 'name': next_mineral.name}}
    elif not next_mineral:
        return {'previous': {'id': prev_mineral.id, 'name': prev_mineral.name}}
    else:
        return {'next': {'id': next_mineral.id, 'name': next_mineral.name},
                'previous': {'id': prev_mineral.id, 'name': prev_mineral.name}}

minerals/templates/minerals/mineral_detail.html
{% extends "layout.html" %}
{% load static %}
{% load minerals_extras %}

{% block content %}
<div class="grid-100 mineral__container">
    <div>
        {% if prev_next|get_item:'previous' %}
            <a class="minerals__anchor mineral__detail_header" href="{% url 'minerals:mineral_detail' prev_next|get_item:'previous'|get_item:'id' %}"><< {{ prev_next|get_item:'previous'|get_item:'name' }}</a>
        {% else %}
            <span class="minerals__anchor mineral__detail_header"><< No previous minerals</span>
        {% endif %}
        <h1 class="mineral__name mineral__detail_header">{{ mineral.name }}</h1>
        {% if prev_next|get_item:'next' %}
            <a class="minerals__anchor mineral__detail_header" href="{% url 'minerals:mineral_detail' prev_next|get_item:'next'|get_item:'id' %}">{{ prev_next|get_item:'next'|get_item:'name' }} >></a>
        {% else %}
            <span class="minerals__anchor mineral__detail_header">No next minerals >></span>
        {% endif %}
    </div>
    <div class="mineral__image-bg">
        <img class="mineral__image" src="{% static 'img' %}/{{ mineral.name }}.jpg">
        <p class="mineral__caption">{{ mineral.image_caption }}</p>
    </div>
    <div class="mineral__table-container">
        <table class="mineral__table">
            {% for key, value in mineral.items %}
                {% if value and key in names %}
                <tr>
                    <td class="mineral__category">{{ key|title|rem_underscore }}</td>
                    <td>{{ value|safe }}</td>
                </tr>
                {% endif %}
            {% endfor %}
        </table>
    </div>
</div>
{% endblock %}

minerals/templates/minerals/mineral_list.html
{% extends "layout.html" %}

{% block content %}
<div class="grid-100">
    <ul class="minerals__container">
        {% for mineral in minerals %}
        <li class="minerals__item">
            <a class="minerals__anchor" href="{% url 'minerals:mineral_detail' mineral_id=mineral.id %}">{{ mineral.name }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/index.html
{% extends "layout.html" %}

{% block content %}
<h1>Welcome!</h1>
<a class="minerals__anchor" href="{% url 'minerals:mineral_list' %}">View all minerals</a>
{% endblock %}

templates/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Josh's Geodes: A series of sedentary sediments</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href='https://fonts.googleapis.com/css?family=Work+Sans:400,500' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Cousine' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
</head>
<body>
    <div class="bounds">
        <div class="grid-100">
            <a href="{% url 'minerals:mineral_list' %}">
                <svg class="logo" viewBox="0 0 127.6 84.8" preserveAspectRation="xMinYMin meet">
                    <polygon points="42.7,84.8 49.6,79.4 40,62.5 51.2,43.5 51.2,43.5 25,0 0,55.6 "/>
                    <polygon class="logo--middle" points="52.9,79.5 52.9,79.5 84.8,80.1 59.7,35 43.3,62.4 "/>
                    <polygon points="127.6,61.4 127.6,61.4 110.3,13.5 110.3,13.5 70.3,48.1 70.3,48.1 88.3,80.5 95.3,81.4 95.3,81.4 "/>
                </svg>
                <h1 class="logo__name text-centered">Josh's Geodes</h1>
            </a>
            <p class="logo__text text-centered">A series of sedentary sediments</p>
        </div>
        {% block content %}{% endblock %}
    </div>
    <div class="minerals__random">
        <a class="minerals__anchor" href="{% url 'minerals:random_mineral' %}">Show random mineral</a>
    </div>
</body>
</html>